[build.env]
passthrough = ["ENABLE_PYO3"]

[target.x86_64-unknown-linux-gnu]
image = "alixinne/cross:x86_64-bullseye"

[target.arm-unknown-linux-gnueabihf]
image = "alixinne/cross:raspberrypi-bookworm"
