on:
  push:
    branches:
      - master

env:
  ENABLE_PYO3: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - arm-unknown-linux-gnueabihf

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --all-features --target ${{ matrix.target }}
